GUI/Areas/Admin/Controllers/LotteryController.cs
using GUI.Areas.Admin.Utilities;
using GUI.Utilities;
using Infrastructure.Interfaces;
using Infrastructure.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.IO;
using System.Threading.Tasks;

namespace GUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class LotteryController : BaseController
    {
        private ILotteryRepository _lotteryRepository;
        private IWebHostEnvironment _hostEnvironment;

        public LotteryController(ILotteryRepository lotteryRepository, IWebHostEnvironment hostEnvironment)
        {
            _lotteryRepository = lotteryRepository;
            _hostEnvironment = hostEnvironment;
        }
        public IActionResult Lotteries()
        {
            return View();
        }
        public async Task<IActionResult> LotteryPartial(int PageIndex = 1, int PageSize = 10, string SearchTerm = "")
        {
            return PartialView("_LotteryPartial", await _lotteryRepository.LotteryGetAll(SearchTerm, PageIndex, PageSize));
        }
        [HttpGet]
        public async Task<IActionResult> LotteryAddUpdate(int id)
        {
            if (id > 0)
            {
                var model = await _lotteryRepository.LotteryGetById(id);
                return PartialView("_LotteryAddUpdate", model);
            }
            else
            {
                return PartialView("_LotteryAddUpdate", new LotteryCreateVM());
            }
        }
        [HttpPost]
        public async Task<IActionResult> LotteryAddUpdate(LotteryCreateVM model)
        {
            model.ExpiryDate = DateTime.Now;
            var RootPathForFile = _hostEnvironment.WebRootPath + "\\LotteryFiles\\LotteryImages";
            if (ModelState.IsValid)
            {
                if (model.Id > 0)
                {
                    if (model.TempLotteryImg != null)
                    {
                        string FileUniqueName = FileHandeling.GetUniqueFileName(model.TempLotteryImg.FileName);
                        model.LotteryImgName = FileUniqueName;
                        var FileUploadPath = Path.Combine(RootPathForFile + "\\" + FileUniqueName);
                        using (FileStream Upload = new FileStream(Path.Combine(FileUploadPath), FileMode.Create))
                        {
                            model.TempLotteryImg.CopyTo(Upload);
                            Upload.Dispose();
                            Upload.Close();
                        }
                    }
                    var resutl = await _lotteryRepository.LotteryUpdate(model);
                    if (resutl == true)
                    {
                        return Json("LotteryPartialButton");
                    }
                    else
                    {
                        return Json("error");
                    }
                }
                else
                {
                    if(model.LotteryImg == null)
                    {
                        model.LotteryImgName = "temp.webp";
                    }
                    else
                    {
                        string FileUniqueName = FileHandeling.GetUniqueFileName(model.LotteryImg.FileName);
                        model.LotteryImgName = FileUniqueName;
                        var FileUploadPath = Path.Combine(RootPathForFile + "\\" + FileUniqueName);
                        using (FileStream Upload = new FileStream(Path.Combine(FileUploadPath), FileMode.Create))
                        {
                            model.LotteryImg.CopyTo(Upload);
                            Upload.Dispose();
                            Upload.Close();
                        }
                    }
                    var resutl = await _lotteryRepository.LotteryCreate(model);
                    if (resutl == true)
                    {
                        return Json("LotteryPartialButton");
                    }
                    else
                    {
                        return Json("error");
                    }
                }
            }
            else
            {
                return Json("");
            }
        }
        [HttpGet]
        public async Task<IActionResult> LotteryDelete(int id)
        {
            var result = await _lotteryRepository.LotteryDelete(id);
            if (result == true)
            {
                return Json("LotteryPartialButton");
            }
            else
            {
                Json("error");
            }
            return Json("");
        }
        #region Lottery Winners
        public IActionResult Winners()
        {
            return View();
        }
        public async Task<IActionResult> WinnersPartial(int PageIndex = 1, int PageSize = 10, string SearchTerm = "")
        {
            return PartialView("_WinnersPartial", await _lotteryRepository.LotteryWinnerLotteryGetAll(SearchTerm, PageIndex, PageSize));
        }
        #endregion

    }
}

GUI/Controllers/LotteryController.cs
using DbModels;
using GUI.Utilities;
using Infrastructure.Interfaces;
using Infrastructure.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using System;
using System.Threading.Tasks;

namespace GUI.Controllers
{
    [Route("api/")]
    [ApiController]
    public class LotteryController : Controller
    {
        private ILotteryRepository _lotteryRepository;

        public LotteryController(ILotteryRepository lotteryRepository)
        {
            _lotteryRepository = lotteryRepository;
        }
        [HttpGet]
        [Route("LotteryGetAll")]
        public async Task<IActionResult> LotteryGetAll()
        {
            var result = await _lotteryRepository.AppLotteryGetAll();
            if (result != null)
            {
                var Response = new ResponseModel()
                {
                    Message = "Available",
                    Status = ReasonPhrases.GetReasonPhrase(StatusCodes.Status200OK),
                    StatusCode = StatusCodes.Status200OK,
                    Data = result
                };
                return new JsonResult(Response);
            }
            else
            {
                var Response = new ResponseModel()
                {
                    Message = "Not Available",
                    Status = ReasonPhrases.GetReasonPhrase(StatusCodes.Status404NotFound),
                    StatusCode = StatusCodes.Status404NotFound,
                };
                return new JsonResult(Response);
            }
        }
        [HttpPost]
        [Route("EnroleLottery")]
        public async Task<IActionResult> EnroleLottery([FromBody] EnroleLotteryVM model)
        {
            if (ModelState.IsValid)
            {
                var candidateCount = await _lotteryRepository.CandidateCount(model.LotteryId);
                if (candidateCount.Difference == 0)
                {
                    var LimitFullResponse = new ResponseModel()
                    {
                        Message = "Token Limit is Full!",
                        Status = ReasonPhrases.GetReasonPhrase(StatusCodes.Status404NotFound),
                        StatusCode = StatusCodes.Status404NotFound,
                    };
                    return new JsonResult(LimitFullResponse);
                }
                else
                {
                    var Entity = new LotteryCandidate()
                    {
                        AppUserId = model.AppUserId,
                        CreatedDate = DateTime.Now,
                        LotteryId = model.LotteryId,
                    };
                    var result = await _lotteryRepository.LotteryCandidateCreate(Entity);
                    if (result == true)
                    {
                        var WinnerCandidateCount = await _lotteryRepository.CandidateCount(model.LotteryId);
                        if (WinnerCandidateCount.Difference == 0)
                        {
                            //    Creating Lottery Winner in Sql                     
                            var LotteryWinnerId = await _lotteryRepository.LotteryCandidateAnnonce(model.LotteryId);
                            //    var CandidatesList = await _lotteryRepository.LotteryCandidateList(model.LotteryId);
                            //    var RandomWinnder = EnumerableExtension.PickRandom<LotteryCandidate>(CandidatesList);
                            //    var LotteryWiner = new LotteryWiner()
                            //    {
                            //        CreatedDate = DateTime.Now,
                            //        LotteryId = model.LotteryId,
                            //        WinerId = 0
                            //    };
                            //    if (RandomWinnder != null && RandomWinnder.Id > 0)
                            //    {
                            //        LotteryWiner.WinerId = RandomWinnder.Id;
                            //    }
                            //    var WinnerCreate = await _lotteryRepository.LotteryWinerCreate(LotteryWiner);
                        }
                        var SuccessResponse = new ResponseModel()
                        {
                            Message = "User Successfully Enrolled!",
                            Status = ReasonPhrases.GetReasonPhrase(StatusCodes.Status200OK),
                            StatusCode = StatusCodes.Status200OK,
                            Data = model
                        };
                        return new JsonResult(SuccessResponse);
                    }
                    else
                    {
                        var ErrorResponse = new ResponseModel()
                        {
                            Message = "Something Went Wrong!",
                            Status = ReasonPhrases.GetReasonPhrase(StatusCodes.Status400BadRequest),
                            StatusCode = StatusCodes.Status400BadRequest,
                        };
                        return new JsonResult(ErrorResponse);
                    }
                }
            }
            var Response = new ResponseModel()
            {
                Message = "Please Provide All Information!",
                Status = ReasonPhrases.GetReasonPhrase(StatusCodes.Status200OK),
                StatusCode = StatusCodes.Status200OK,
            };
            return new JsonResult(Response);
        }
        [HttpGet]
        [Route("LotteryWinnerGetAll")]
        public async Task<IActionResult> LotteryWinnerGetAll()
        {
            var result = await _lotteryRepository.AppLotteryWinnerGetAll();
            if (result != null)
            {
                var Response = new ResponseModel()
                {
                    Message = "Available",
                    Status = ReasonPhrases.GetReasonPhrase(StatusCodes.Status200OK),
                    StatusCode = StatusCodes.Status200OK,
                    Data = result
                };
                return new JsonResult(Response);
            }
            else
            {
                var Response = new ResponseModel()
                {
                    Message = "Not Available",
                    Status = ReasonPhrases.GetReasonPhrase(StatusCodes.Status404NotFound),
                    StatusCode = StatusCodes.Status404NotFound,
                };
                return new JsonResult(Response);
            }
        }
    }
}

GUI/Areas/Admin/Views/Lottery/Lotteries.cshtml
<div class="pageheader">
    <div class="media">
        <div class="pageicon pull-left">
            <i class="fa fa-th-list"></i>
        </div>
        <div class="media-body">
            <ul class="breadcrumb">
                <li><a asp-area="admin" asp-controller="Home" asp-action="Index"><i class="glyphicon glyphicon-home"></i></a></li>
                <li>Lottery</li>
                <li>Lottries</li>
            </ul>
            <h4>Lottries</h4>
        </div>
    </div><!-- media -->
</div>
<div class="contentpanel">
    <div class="row">
        <div class="col-md-12">
            <div class="well mt10">
                <div class="row">
                    <div class="col-sm-9">
                        <input id="GenericPagingSearchInput" type="text" placeholder="What are you looking for?" class="form-control">
                    </div>
                    <div class="col-sm-3">
                        <button class="btn btn-primary btn-metro" id="btnGenericPagingSearch">
                            <i class="fa  fa-search"></i>
                        </button>
                        <button id="/Admin/Lottery/LotteryAddUpdate?id=0" class="GenericAddEntity btn btn-primary btn-metro">
                            <i class="fa fa-plus"></i>
                        </button>
                    </div>
                </div>
            </div>

            <div id="LotteryResultDiv">
            </div>
        </div>
    </div>
</div>
<button id="LotteryPartialButton" style="display:none;"></button>
<input hidden id="PagingDataUpdatingDiv" value="LotteryResultDiv" />
@section Scripts
    {
    <script>
        $(document).ready(function () {
            $('#LotteryPartialButton').click();
        });
        $('#LotteryPartialButton').click(function () {
            $.get("/Admin/Lottery/LotteryPartial", function (res) {
                $('#LotteryResultDiv').html(res);
            });
        });
    </script>
}

GUI/Areas/Admin/Views/Lottery/Winners.cshtml
<div class="pageheader">
    <div class="media">
        <div class="pageicon pull-left">
            <i class="fa fa-th-list"></i>
        </div>
        <div class="media-body">
            <ul class="breadcrumb">
                <li><a asp-area="admin" asp-controller="Home" asp-action="Index"><i class="glyphicon glyphicon-home"></i></a></li>
                <li>Lottery</li>
                <li>Winners</li>
            </ul>
            <h4>Lottery Winners</h4>
        </div>
    </div><!-- media -->
</div>
<div class="contentpanel">
    <div class="row">
        <div class="col-md-12">
            <div class="well mt10">
                <div class="row">
                    <div class="col-sm-9">
                        <input id="GenericPagingSearchInput" type="text" placeholder="What are you looking for?" class="form-control">
                    </div>
                    <div class="col-sm-3">
                        <button class="btn btn-primary btn-metro" id="btnGenericPagingSearch">
                            <i class="fa  fa-search"></i>
                        </button>
                    </div>
                </div>
            </div>

            <div id="LotteryWinnerResultDiv">
            </div>
        </div>
    </div>
</div>
<button id="LotteryWinnerPartialButton" style="display:none;"></button>
<input hidden id="PagingDataUpdatingDiv" value="LotteryWinnerResultDiv" />
@section Scripts
    {
    <script>
        $(document).ready(function () {
            $('#LotteryWinnerPartialButton').click();
        });
        $('#LotteryWinnerPartialButton').click(function () {
            $.get("/Admin/Lottery/WinnersPartial", function (res) {
                $('#LotteryWinnerResultDiv').html(res);
            });
        });
    </script>
}

GUI/Areas/Admin/Views/Lottery/_LotteryAddUpdate.cshtml
@model Infrastructure.ViewModels.LotteryCreateVM
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
            @if (Model.Id > 0)
            {
                <h4 class="modal-title">
                    Edit Lottery
                </h4>
            }
            else
            {
                <h4 class="modal-title">
                    Add Lottery
                </h4>
            }
        </div>
        <div class="modal-body">
            <div class="row">

                <form id="GenericForm" method="post" asp-area="Admin" asp-controller="Lottery" asp-action="LotteryAddUpdate" data-ajax="true" data-ajax-begin="OnBegin" data-ajax-success="OnSuccess" data-ajax-failure="OnFailure" enctype="multipart/form-data">
                    @if (Model.Id > 0)
                    {
                        @Html.HiddenFor(p=>p.Id)
                        @Html.HiddenFor(p=>p.LotteryImg)
                    }

                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">Lotter Name</label>
                            <input asp-for="Name" class="form-control">
                            <span asp-validation-for="Name" class="label label-danger"></span>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">Lotter Reward Price</label>
                            <input asp-for="RewardPrice" class="form-control">
                            <span asp-validation-for="RewardPrice" class="label label-danger"></span>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">Lotter Token Limit</label>
                            <input asp-for="TokenLimit" class="form-control">
                            <span asp-validation-for="TokenLimit" class="label label-danger"></span>
                        </div>
                    </div>

                    <div class="col-sm-6">
                        @if (Model.Id > 0)
                        {
                            <div class="form-group">
                                <label class="control-label">Lottery Imgage</label>
                                <input asp-for="TempLotteryImg" class="form-control">
                                <span asp-validation-for="TempLotteryImg" class="label label-danger"></span>
                            </div>
                        }
                        else
                        {
                            <div class="form-group">
                                <label class="control-label">Lottery Imgage</label>
                                <input asp-for="LotteryImg" class="form-control">
                                <span asp-validation-for="LotteryImg" class="label label-danger"></span>
                            </div>
                        }
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label class="control-label">Lottery Description</label>
                            <input asp-for="Description" class="form-control">
                            <span asp-validation-for="Description" class="label label-danger"></span>
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Is Recursive</label>
                            <div class="col-sm-9">
                                <input asp-for="IsRecursive" class="form-control">
                                <span asp-validation-for="IsRecursive"  class="label label-danger"></span>
                            </div><!-- col-sm-8 -->
                        </div>

                    </div>
                    @*<div class="col-sm-6">
                    <div class="form-group">
                    <label class="control-label">Lotter Expiry Date</label>
                    <input asp-for="ExpiryDate" class="form-control">
                    <span asp-validation-for="ExpiryDate" class="label label-danger"></span>
                    </div>
                    </div>*@
                    @if (Model.Id > 0 && Model.LotteryImgName != "temp.webp")
                    {
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="control-label">Old Lottery Picture</label>
                                <img width="100" height="100" src="~/LotteryFiles/LotteryImages/@Model.LotteryImgName">
                            </div>
                        </div>
                    }
                </form>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light-primary font-weight-bold" data-dismiss="modal">Close</button>
                <button type="button" onclick="SubmitForm()" id="SubmitButttonId" class="btn btn-primary font-weight-bold">Submit</button>
            </div>
        </div>
    </div>
</div>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        jQuery.validator.unobtrusive.parse("#GenericForm");
    });
</script>

GUI/Areas/Admin/Views/Lottery/_LotteryPartial.cshtml
@model Infrastructure.Utilities.PagingModel<Infrastructure.ViewModels.LotteryVM>
<input id="GenericPagingDataUrl" value="/Admin/Lottery/LotteryPartial" type="hidden" />
<div class="table-responsive">
    <table class="table table-primary table-striped mb30" id="">
        <thead>
            <tr>
                <th>#</th>
                <th>Img</th>
                <th>Name</th>
                <th>Token Limit</th>
                <th>Reward Price</th>
                <th>Total Applied User</th>
                <th>is Recursive</th>
                @*<th>Expriry Date</th>*@
                <th>Description</th>
                <th>
                    Is open?
                </th>
                <th class="text-right">Action</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Data != null && Model.Data.Count() > 0)
            {
                int index = 1;
                foreach (var item in Model.Data)
                {
                    <tr>
                        <td>
                            <span class="badge badge-primary">@index</span>
                        </td>
                        <td>
                            <div class="pull-left">
                                <img width="55" height="55" class="img-circle img-online" src="@item.LotteryImgPath" alt="not Uploaded">
                            </div>
                        </td>
                        <td>@item.Name</td>
                        <td>
                            @item.TokenLimit
                        </td>
                        <td>
                            @item.RewardPrice
                        </td>
                        <td>
                            @item.TotalApplied
                        </td>
                        <td>
                            @if (item.IsRecursive)
                            {
                                <span class="label label-success">Yes</span>
                            }
                            else
                            {
                                <span class="label label-warning">No</span>
                            }
                        </td>
                        @*<td>
                @item.ExpiryDate
                </td>*@
                        <td>
                            @item.Description
                        </td>
                        <td>
                            @if (item.IsOpened)
                            {
                                <span class="label label-success">Opened</span>
                            }
                            else
                            {
                                <span class="label label-warning">Not Opened</span>
                            }
                        </td>
                        <td class="text-right">
                            <button class="btn btn-xs btn-success" onclick="GenericEdit(this)" id="/Admin/Lottery/LotteryAddUpdate?id=@item.Id">
                                <i class="fa fa-pencil"></i>
                            </button>
                            |
                            <button class="btn btn-xs btn-danger" onclick="GenericDelete(this)" id="/Admin/Lottery/LotteryDelete?id=@item.Id">
                                <i class="fa fa-trash-o"></i>
                            </button>
                        </td>
                    </tr>
                    index++;
                }
            }
        </tbody>
    </table>
</div><!-- table-responsive -->
<div class="alert alert-info">
    <div class="row">
        <div class="col-md-10">
            <ul class="pagination pagination-split pagination-circled nomargin">

                @if (Model.PageIndex > 1)
                {
                    <li class="disabled">
                        <a onclick="GetDataByPage(1)" href="#"><i class="fa fa-angle-left"></i></a>
                    </li>
                }
                else
                {
                    <li class="disabled"><a href="#"><i class="fa fa-angle-left"></i></a></li>
                }
                @{
                    var currentPage = Model.PageIndex;
                    var pageCount = Model.RecordCount / Model.PageSize;
                    int remainder = Model.RecordCount % Model.PageSize;
                    if (remainder > 0)
                    {
                        pageCount = pageCount + 1;
                    }
                    // How many pages views right or left of currentPage
                    const int PageLeft = 2;
                    const int PagesRight = 2;

                    // get first page befor ...
                    var fromPage = Math.Max(1, currentPage - PageLeft);

                    // get last page after ...
                    var toPage = Math.Min(pageCount, currentPage + PagesRight);

                    if (pageCount - toPage == 1)
                    {
                        toPage = pageCount;
                    }

                    if (fromPage > 1)
                    {
                    // view First page
                        <li><a href="#" onclick="GetDataByPage(1)">1</a></li>
                        if (fromPage > 2)
                        {
                            // view first ...
                            // calculate number page for link ..., it's middle between first page and fromPage
                            var middleNumber = (int)Math.Ceiling((double)(fromPage - 2) / 2) + 1;
                            <li><a href="#" onclick="GetDataByPage(@middleNumber)">...</a></li>
                        }
                    }
                    // view paginator between currentPage
                    for (int i = fromPage; i <= toPage; i++)
                    {
                        if (currentPage == i)
                        {
                            <li class="active"><a href="#" onclick="GetDataByPage(@i)">@i</a></li>
                        }
                        else
                        {
                            <li><a href="#" onclick="GetDataByPage(@i)">@i</a></li>
                        }
                    }
                    // view second ...
                    if (toPage < pageCount)
                    {
                        int middleNumber = (int)Math.Ceiling((double)(pageCount - toPage) / 2) + toPage;
                        <li><a href="#" onclick="GetDataByPage(@middleNumber)">...</a></li>
                        // view last page
                        if (toPage < pageCount - 1)
                        {
                            <li><a href="#" onclick="GetDataByPage(@pageCount)">@pageCount</a></li>
                        }
                    }

                    @if (Model.PageIndex < pageCount)
                    {
                        <li><a href="#" onclick="GetDataByPage(@Model.PageIndex + 1)"><i class="fa fa-angle-right"></i></a></li>
                    }
                    else
                    {
                        <li class="disabled"><a href="#"><i class="fa fa-angle-right"></i></a></li>
                    }


                }
            </ul>
            <br />
            <span class="text-muted">Displaying 10 of @Model.RecordCount records</span>
        </div>
        <div class="col-md-2">
            <div class="d-flex align-items-center">
                <select id="GenericPageItemDropdown" asp-for="@Model.PageSize" onchange="UpdatePagingData()" class="form-control form-control-sm text-primary font-weight-bold mr-4 border-0 bg-light-primary" style="width: 75px;">
                    <option value="5">5</option>
                    <option value="10">10</option>
                    <option value="20">20</option>
                    <option value="30">30</option>
                    <option value="40">40</option>
                    <option value="50">50</option>
                </select>
            </div>
        </div>
    </div>
</div>